# Imagen base PHP + FPM
FROM php:8.2-fpm

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    git curl unzip libpng-dev libjpeg-dev libfreetype6-dev \
    libonig-dev libzip-dev zip \
    && docker-php-ext-install pdo_mysql mbstring zip

# GD para Laravel y Spatie
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd

# Fileinfo
RUN docker-php-ext-install fileinfo

# Instalar Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Configurar directorio del proyecto
WORKDIR /var/www/html

# Copiar código de Laravel API
COPY . .

# Instalar dependencias PHP
RUN composer install --no-dev --optimize-autoloader

RUN php artisan config:cache || true

# Permisos si usas storage
RUN chown -R www-data:www-data storage bootstrap/cache

EXPOSE 8000

# No generes APP_KEY en build; hazlo en Render Shell o en Variables
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
