export const words = [
  "Innovación",
  "Creatividad",
  "Accesibilidad",
  "Experiencia",
  "Oportunidad",
  "Interacción",
  "Comodidad",
  "al alcance",
  "de tu mano",
  "COMBI-UEES",
  "Diseño",
  "Cambio",
  "COMBI-UEES",
  "Comodidad",
  "al alcance",
  "de tu mano",
  "Innovación",
  "Creatividad",
  "Accesibilidad",
  "Experiencia",
  "Oportunidad",
  "Interacción",
  "Diseño",
  "Cambio",
  "COMBI-UEES",
  "Accesibilidad",
  "experiencia",
  "oportunidad",
  "interacción",
  "diseño",
  "cambio",
  "COMBI-UEES",
];
